'use strict';

angular.module('perfectteamApp')
  .constant('githubdata', [
  {
    "url": "https://api.github.com/repos/paszin/drleeslab/issues/5",
    "repository_url": "https://api.github.com/repos/paszin/drleeslab",
    "labels_url": "https://api.github.com/repos/paszin/drleeslab/issues/5/labels{/name}",
    "comments_url": "https://api.github.com/repos/paszin/drleeslab/issues/5/comments",
    "events_url": "https://api.github.com/repos/paszin/drleeslab/issues/5/events",
    "html_url": "https://github.com/paszin/drleeslab/issues/5",
    "id": 176237367,
    "number": 5,
    "title": "Add Facebook Login",
    "user": {
      "login": "paszin",
      "id": 9304382,
      "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paszin",
      "html_url": "https://github.com/paszin",
      "followers_url": "https://api.github.com/users/paszin/followers",
      "following_url": "https://api.github.com/users/paszin/following{/other_user}",
      "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
      "organizations_url": "https://api.github.com/users/paszin/orgs",
      "repos_url": "https://api.github.com/users/paszin/repos",
      "events_url": "https://api.github.com/users/paszin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paszin/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "judithyueli",
      "id": 3580992,
      "avatar_url": "https://avatars.githubusercontent.com/u/3580992?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/judithyueli",
      "html_url": "https://github.com/judithyueli",
      "followers_url": "https://api.github.com/users/judithyueli/followers",
      "following_url": "https://api.github.com/users/judithyueli/following{/other_user}",
      "gists_url": "https://api.github.com/users/judithyueli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/judithyueli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/judithyueli/subscriptions",
      "organizations_url": "https://api.github.com/users/judithyueli/orgs",
      "repos_url": "https://api.github.com/users/judithyueli/repos",
      "events_url": "https://api.github.com/users/judithyueli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/judithyueli/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "judithyueli",
        "id": 3580992,
        "avatar_url": "https://avatars.githubusercontent.com/u/3580992?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/judithyueli",
        "html_url": "https://github.com/judithyueli",
        "followers_url": "https://api.github.com/users/judithyueli/followers",
        "following_url": "https://api.github.com/users/judithyueli/following{/other_user}",
        "gists_url": "https://api.github.com/users/judithyueli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/judithyueli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/judithyueli/subscriptions",
        "organizations_url": "https://api.github.com/users/judithyueli/orgs",
        "repos_url": "https://api.github.com/users/judithyueli/repos",
        "events_url": "https://api.github.com/users/judithyueli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/judithyueli/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-09-11T10:33:21Z",
    "updated_at": "2016-09-11T10:33:31Z",
    "closed_at": null,
    "body": ""
  },
  {
    "url": "https://api.github.com/repos/paszin/drleeslab/issues/4",
    "repository_url": "https://api.github.com/repos/paszin/drleeslab",
    "labels_url": "https://api.github.com/repos/paszin/drleeslab/issues/4/labels{/name}",
    "comments_url": "https://api.github.com/repos/paszin/drleeslab/issues/4/comments",
    "events_url": "https://api.github.com/repos/paszin/drleeslab/issues/4/events",
    "html_url": "https://github.com/paszin/drleeslab/issues/4",
    "id": 176224707,
    "number": 4,
    "title": "Add Google Analytics",
    "user": {
      "login": "paszin",
      "id": 9304382,
      "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paszin",
      "html_url": "https://github.com/paszin",
      "followers_url": "https://api.github.com/users/paszin/followers",
      "following_url": "https://api.github.com/users/paszin/following{/other_user}",
      "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
      "organizations_url": "https://api.github.com/users/paszin/orgs",
      "repos_url": "https://api.github.com/users/paszin/repos",
      "events_url": "https://api.github.com/users/paszin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paszin/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/paszin/drleeslab/labels/Integration",
        "name": "Integration",
        "color": "d93f0b"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "y1y",
      "id": 12815350,
      "avatar_url": "https://avatars.githubusercontent.com/u/12815350?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/y1y",
      "html_url": "https://github.com/y1y",
      "followers_url": "https://api.github.com/users/y1y/followers",
      "following_url": "https://api.github.com/users/y1y/following{/other_user}",
      "gists_url": "https://api.github.com/users/y1y/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/y1y/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/y1y/subscriptions",
      "organizations_url": "https://api.github.com/users/y1y/orgs",
      "repos_url": "https://api.github.com/users/y1y/repos",
      "events_url": "https://api.github.com/users/y1y/events{/privacy}",
      "received_events_url": "https://api.github.com/users/y1y/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "y1y",
        "id": 12815350,
        "avatar_url": "https://avatars.githubusercontent.com/u/12815350?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/y1y",
        "html_url": "https://github.com/y1y",
        "followers_url": "https://api.github.com/users/y1y/followers",
        "following_url": "https://api.github.com/users/y1y/following{/other_user}",
        "gists_url": "https://api.github.com/users/y1y/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/y1y/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/y1y/subscriptions",
        "organizations_url": "https://api.github.com/users/y1y/orgs",
        "repos_url": "https://api.github.com/users/y1y/repos",
        "events_url": "https://api.github.com/users/y1y/events{/privacy}",
        "received_events_url": "https://api.github.com/users/y1y/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-09-11T06:30:50Z",
    "updated_at": "2016-09-11T07:19:24Z",
    "closed_at": null,
    "body": "[Disclaimer: This is not a real issue, it`s for another demo. Please do not change this]\r\nIntegrate Google Analytics to track user behaviour."
  },
  {
    "url": "https://api.github.com/repos/paszin/drleeslab/issues/3",
    "repository_url": "https://api.github.com/repos/paszin/drleeslab",
    "labels_url": "https://api.github.com/repos/paszin/drleeslab/issues/3/labels{/name}",
    "comments_url": "https://api.github.com/repos/paszin/drleeslab/issues/3/comments",
    "events_url": "https://api.github.com/repos/paszin/drleeslab/issues/3/events",
    "html_url": "https://github.com/paszin/drleeslab/issues/3",
    "id": 152950570,
    "number": 3,
    "title": "Add marker for custom friends location",
    "user": {
      "login": "paszin",
      "id": 9304382,
      "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paszin",
      "html_url": "https://github.com/paszin",
      "followers_url": "https://api.github.com/users/paszin/followers",
      "following_url": "https://api.github.com/users/paszin/following{/other_user}",
      "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
      "organizations_url": "https://api.github.com/users/paszin/orgs",
      "repos_url": "https://api.github.com/users/paszin/repos",
      "events_url": "https://api.github.com/users/paszin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paszin/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "url": "https://api.github.com/repos/paszin/drleeslab/labels/feature",
        "name": "feature",
        "color": "f9d0c4"
      },
      {
        "url": "https://api.github.com/repos/paszin/drleeslab/labels/UI",
        "name": "UI",
        "color": "bfdadc"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "paszin",
      "id": 9304382,
      "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paszin",
      "html_url": "https://github.com/paszin",
      "followers_url": "https://api.github.com/users/paszin/followers",
      "following_url": "https://api.github.com/users/paszin/following{/other_user}",
      "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
      "organizations_url": "https://api.github.com/users/paszin/orgs",
      "repos_url": "https://api.github.com/users/paszin/repos",
      "events_url": "https://api.github.com/users/paszin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paszin/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "paszin",
        "id": 9304382,
        "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/paszin",
        "html_url": "https://github.com/paszin",
        "followers_url": "https://api.github.com/users/paszin/followers",
        "following_url": "https://api.github.com/users/paszin/following{/other_user}",
        "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
        "organizations_url": "https://api.github.com/users/paszin/orgs",
        "repos_url": "https://api.github.com/users/paszin/repos",
        "events_url": "https://api.github.com/users/paszin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/paszin/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-05-04T08:00:09Z",
    "updated_at": "2016-09-11T07:19:06Z",
    "closed_at": null,
    "body": ""
  },
  {
    "url": "https://api.github.com/repos/paszin/drleeslab/issues/2",
    "repository_url": "https://api.github.com/repos/paszin/drleeslab",
    "labels_url": "https://api.github.com/repos/paszin/drleeslab/issues/2/labels{/name}",
    "comments_url": "https://api.github.com/repos/paszin/drleeslab/issues/2/comments",
    "events_url": "https://api.github.com/repos/paszin/drleeslab/issues/2/events",
    "html_url": "https://github.com/paszin/drleeslab/issues/2",
    "id": 152022483,
    "number": 2,
    "title": "show tweets on map",
    "user": {
      "login": "paszin",
      "id": 9304382,
      "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paszin",
      "html_url": "https://github.com/paszin",
      "followers_url": "https://api.github.com/users/paszin/followers",
      "following_url": "https://api.github.com/users/paszin/following{/other_user}",
      "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
      "organizations_url": "https://api.github.com/users/paszin/orgs",
      "repos_url": "https://api.github.com/users/paszin/repos",
      "events_url": "https://api.github.com/users/paszin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paszin/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "oveou",
      "id": 5498486,
      "avatar_url": "https://avatars.githubusercontent.com/u/5498486?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/oveou",
      "html_url": "https://github.com/oveou",
      "followers_url": "https://api.github.com/users/oveou/followers",
      "following_url": "https://api.github.com/users/oveou/following{/other_user}",
      "gists_url": "https://api.github.com/users/oveou/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/oveou/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/oveou/subscriptions",
      "organizations_url": "https://api.github.com/users/oveou/orgs",
      "repos_url": "https://api.github.com/users/oveou/repos",
      "events_url": "https://api.github.com/users/oveou/events{/privacy}",
      "received_events_url": "https://api.github.com/users/oveou/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "oveou",
        "id": 5498486,
        "avatar_url": "https://avatars.githubusercontent.com/u/5498486?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/oveou",
        "html_url": "https://github.com/oveou",
        "followers_url": "https://api.github.com/users/oveou/followers",
        "following_url": "https://api.github.com/users/oveou/following{/other_user}",
        "gists_url": "https://api.github.com/users/oveou/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/oveou/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/oveou/subscriptions",
        "organizations_url": "https://api.github.com/users/oveou/orgs",
        "repos_url": "https://api.github.com/users/oveou/repos",
        "events_url": "https://api.github.com/users/oveou/events{/privacy}",
        "received_events_url": "https://api.github.com/users/oveou/received_events",
        "type": "User",
        "site_admin": false
      },
      {
        "login": "paszin",
        "id": 9304382,
        "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/paszin",
        "html_url": "https://github.com/paszin",
        "followers_url": "https://api.github.com/users/paszin/followers",
        "following_url": "https://api.github.com/users/paszin/following{/other_user}",
        "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
        "organizations_url": "https://api.github.com/users/paszin/orgs",
        "repos_url": "https://api.github.com/users/paszin/repos",
        "events_url": "https://api.github.com/users/paszin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/paszin/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-04-30T10:25:58Z",
    "updated_at": "2016-09-11T10:46:44Z",
    "closed_at": null,
    "body": ""
  },
  {
    "url": "https://api.github.com/repos/paszin/drleeslab/issues/1",
    "repository_url": "https://api.github.com/repos/paszin/drleeslab",
    "labels_url": "https://api.github.com/repos/paszin/drleeslab/issues/1/labels{/name}",
    "comments_url": "https://api.github.com/repos/paszin/drleeslab/issues/1/comments",
    "events_url": "https://api.github.com/repos/paszin/drleeslab/issues/1/events",
    "html_url": "https://github.com/paszin/drleeslab/issues/1",
    "id": 152022471,
    "number": 1,
    "title": "interpolate values for high slider resolution",
    "user": {
      "login": "paszin",
      "id": 9304382,
      "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/paszin",
      "html_url": "https://github.com/paszin",
      "followers_url": "https://api.github.com/users/paszin/followers",
      "following_url": "https://api.github.com/users/paszin/following{/other_user}",
      "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
      "organizations_url": "https://api.github.com/users/paszin/orgs",
      "repos_url": "https://api.github.com/users/paszin/repos",
      "events_url": "https://api.github.com/users/paszin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/paszin/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "Sweetymeow",
      "id": 4945897,
      "avatar_url": "https://avatars.githubusercontent.com/u/4945897?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Sweetymeow",
      "html_url": "https://github.com/Sweetymeow",
      "followers_url": "https://api.github.com/users/Sweetymeow/followers",
      "following_url": "https://api.github.com/users/Sweetymeow/following{/other_user}",
      "gists_url": "https://api.github.com/users/Sweetymeow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Sweetymeow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Sweetymeow/subscriptions",
      "organizations_url": "https://api.github.com/users/Sweetymeow/orgs",
      "repos_url": "https://api.github.com/users/Sweetymeow/repos",
      "events_url": "https://api.github.com/users/Sweetymeow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Sweetymeow/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "Sweetymeow",
        "id": 4945897,
        "avatar_url": "https://avatars.githubusercontent.com/u/4945897?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Sweetymeow",
        "html_url": "https://github.com/Sweetymeow",
        "followers_url": "https://api.github.com/users/Sweetymeow/followers",
        "following_url": "https://api.github.com/users/Sweetymeow/following{/other_user}",
        "gists_url": "https://api.github.com/users/Sweetymeow/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Sweetymeow/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Sweetymeow/subscriptions",
        "organizations_url": "https://api.github.com/users/Sweetymeow/orgs",
        "repos_url": "https://api.github.com/users/Sweetymeow/repos",
        "events_url": "https://api.github.com/users/Sweetymeow/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Sweetymeow/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2016-04-30T10:25:46Z",
    "updated_at": "2016-09-11T10:32:48Z",
    "closed_at": null,
    "body": "i know, what i mean ;)"
  }
]
).constant("ghsubscribers", [
  {
    "login": "paszin",
    "id": 9304382,
    "avatar_url": "https://avatars.githubusercontent.com/u/9304382?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/paszin",
    "html_url": "https://github.com/paszin",
    "followers_url": "https://api.github.com/users/paszin/followers",
    "following_url": "https://api.github.com/users/paszin/following{/other_user}",
    "gists_url": "https://api.github.com/users/paszin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/paszin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/paszin/subscriptions",
    "organizations_url": "https://api.github.com/users/paszin/orgs",
    "repos_url": "https://api.github.com/users/paszin/repos",
    "events_url": "https://api.github.com/users/paszin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/paszin/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "clarkjung",
    "id": 4378440,
    "avatar_url": "https://avatars.githubusercontent.com/u/4378440?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/clarkjung",
    "html_url": "https://github.com/clarkjung",
    "followers_url": "https://api.github.com/users/clarkjung/followers",
    "following_url": "https://api.github.com/users/clarkjung/following{/other_user}",
    "gists_url": "https://api.github.com/users/clarkjung/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/clarkjung/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/clarkjung/subscriptions",
    "organizations_url": "https://api.github.com/users/clarkjung/orgs",
    "repos_url": "https://api.github.com/users/clarkjung/repos",
    "events_url": "https://api.github.com/users/clarkjung/events{/privacy}",
    "received_events_url": "https://api.github.com/users/clarkjung/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "oveou",
    "id": 5498486,
    "avatar_url": "https://avatars.githubusercontent.com/u/5498486?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/oveou",
    "html_url": "https://github.com/oveou",
    "followers_url": "https://api.github.com/users/oveou/followers",
    "following_url": "https://api.github.com/users/oveou/following{/other_user}",
    "gists_url": "https://api.github.com/users/oveou/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/oveou/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/oveou/subscriptions",
    "organizations_url": "https://api.github.com/users/oveou/orgs",
    "repos_url": "https://api.github.com/users/oveou/repos",
    "events_url": "https://api.github.com/users/oveou/events{/privacy}",
    "received_events_url": "https://api.github.com/users/oveou/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Sweetymeow",
    "id": 4945897,
    "avatar_url": "https://avatars.githubusercontent.com/u/4945897?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Sweetymeow",
    "html_url": "https://github.com/Sweetymeow",
    "followers_url": "https://api.github.com/users/Sweetymeow/followers",
    "following_url": "https://api.github.com/users/Sweetymeow/following{/other_user}",
    "gists_url": "https://api.github.com/users/Sweetymeow/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Sweetymeow/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Sweetymeow/subscriptions",
    "organizations_url": "https://api.github.com/users/Sweetymeow/orgs",
    "repos_url": "https://api.github.com/users/Sweetymeow/repos",
    "events_url": "https://api.github.com/users/Sweetymeow/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Sweetymeow/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "judithyueli",
    "id": 3580992,
    "avatar_url": "https://avatars.githubusercontent.com/u/3580992?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/judithyueli",
    "html_url": "https://github.com/judithyueli",
    "followers_url": "https://api.github.com/users/judithyueli/followers",
    "following_url": "https://api.github.com/users/judithyueli/following{/other_user}",
    "gists_url": "https://api.github.com/users/judithyueli/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/judithyueli/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/judithyueli/subscriptions",
    "organizations_url": "https://api.github.com/users/judithyueli/orgs",
    "repos_url": "https://api.github.com/users/judithyueli/repos",
    "events_url": "https://api.github.com/users/judithyueli/events{/privacy}",
    "received_events_url": "https://api.github.com/users/judithyueli/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "y1y",
    "id": 12815350,
    "avatar_url": "https://avatars.githubusercontent.com/u/12815350?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/y1y",
    "html_url": "https://github.com/y1y",
    "followers_url": "https://api.github.com/users/y1y/followers",
    "following_url": "https://api.github.com/users/y1y/following{/other_user}",
    "gists_url": "https://api.github.com/users/y1y/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/y1y/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/y1y/subscriptions",
    "organizations_url": "https://api.github.com/users/y1y/orgs",
    "repos_url": "https://api.github.com/users/y1y/repos",
    "events_url": "https://api.github.com/users/y1y/events{/privacy}",
    "received_events_url": "https://api.github.com/users/y1y/received_events",
    "type": "User",
    "site_admin": false
  }
]
);
